name: Deploy to Hugging Face
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Hugging Face
        uses: huggingface/huggingface_hub@main
        with:
          huggingface_token: ${{ secrets.HUGGINGFACE_TOKEN }}
          huggingface_repo: your-username/ci-cd-anomaly-detection
          git_config_user: "github-actions"
          git_config_email: "github-actions@github.com"